package be.ephec.padel.backend.model.enums;

public enum OrigineMouvementSoldeType {
    LEGACY,
    SEED,
    AJUSTEMENT_MANUEL,
    CREATION_MATCH_ORGANISATEUR,
    AJOUT_MATCH_PRIVE,
    REJOINDRE_MATCH_PUBLIC_PART,
    PAIEMENT_PARTICIPATION,
    RATTRAPAGE_DETTE,
    TRAITEMENT_J1_NEUTRALISATION,
    ANNULATION_MATCH_NEUTRALISATION,
    TRANSFERT_ORGANISATEUR_DEBUT_MATCH
}
