app.seed.enabled=true

app.security.admin.global.username=admin.global.dev
app.security.admin.global.password=admin123
app.security.admin.site.password=admin123
app.security.admin.site.users=admin.site.nord.dev:1
