spring.application.name=backend

spring.datasource.url=jdbc:sqlserver://localhost:14333;databaseName=padel;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
springdoc.enable-spring-security=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


app.security.admin.global.username=${ADMIN_GLOBAL_USERNAME}
app.security.admin.global.password=${ADMIN_GLOBAL_PASSWORD}
app.security.admin.site.password=${ADMIN_SITE_PASSWORD}
app.security.admin.site.users=${ADMIN_SITE_USERS}

